# githttps://docs.travis-ci.com/user/languages/javascript-with-nodejs/ #-- --version version-number
language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
node_js:
  - node
  - "10"
  - "8"
  - "6"
